prototype_labels = {
    '20250407_021157_15_pipnet_s21_stage7_p16': [
        {"prototype": 0, "label":  "Count-1"},
        {"prototype": 1, "label":  "Circ(3)"},
        {"prototype": 2, "label":  "Tri(2, 3)"},
        {"prototype": 3, "label":  "Count-1"},
        {"prototype": 4, "label":  "Circ(:)"},
        {"prototype": 5, "label":  "Dead"},
        {"prototype": 6, "label":  "Tri(1, 3)"},
        {"prototype": 7, "label":  "Hex(3)"},
        {"prototype": 8, "label":  "Circ(2)"},
        {"prototype": 9, "label":  "Hex(2, 3)"},
        {"prototype": 10, "label": "Hex(1)"},
        {"prototype": 11, "label": "Count-2"},
        {"prototype": 12, "label": "Circ(1, 2)"},
        {"prototype": 13, "label": "Hex(1, 2)"},
        {"prototype": 14, "label": "Count-1"},
        {"prototype": 15, "label":  "Dead"}
    ],
    '20250705_111247_9_final_s42_stage7_p16_linear_train': [
        {"prototype": 0, "label":  "Circ(3)"},
        {"prototype": 1, "label":  "Hex(1, 2)"},
        {"prototype": 2, "label":  "Hex(1, 2)"},
        {"prototype": 3, "label":  "Dead"},
        {"prototype": 4, "label":  "Tri(1, 2)"},
        {"prototype": 5, "label":  "Hex(1)"},
        {"prototype": 6, "label":  "Hex(3)"},
        {"prototype": 7, "label":  "Tri(3)"},
        {"prototype": 8, "label":  "Circ(1)"},
        {"prototype": 9, "label":  "Tri(1)"},
        {"prototype": 10, "label": "Tri(1)"},
        {"prototype": 11, "label": "Hex(1)"},
        {"prototype": 12, "label": "Circ(1, 2)"},
        {"prototype": 13, "label": "Circ(1)"},
        {"prototype": 14, "label": "Tri(1)"},
        {"prototype": 15, "label":  "Dead"}
    ],
    '20250706_032740_5_final_s21_stage7_p16_onehot_current_grad_train': [
        {"prototype": 0, "label":  "Tri(:)"},
        {"prototype": 1, "label":  "Tri(:)"},
        {"prototype": 2, "label":  "Tri(:)"},
        {"prototype": 3, "label":  "Circ, Hex"},
        {"prototype": 4, "label":  "Circ(1)"},
        {"prototype": 5, "label":  "Circ(:)"},
        {"prototype": 6, "label":  "Circ, Hex"},
        {"prototype": 7, "label":  "Tri(:)"},
        {"prototype": 8, "label":  "Circ, Hex"},
        {"prototype": 9, "label":  "Hex(:)"},
        {"prototype": 10, "label": "Hex(:)"},
        {"prototype": 11, "label": "Tri(:)"},
        {"prototype": 12, "label": "Circ(:)"},
        {"prototype": 13, "label": "Tri(1)"},
        {"prototype": 14, "label": "Hex(3)"},
        {"prototype": 15, "label":  "Dead"}
    ],
}
