dataset: 'geometric_shapes'
validation_size: 0.0
net: 'convnext_tiny_26'
batch_size: 64
batch_size_pretrain: 128
epochs: 0
epochs_pretrain: 20
optimizer: 'Adam'
lr: 0.01
lr_block: 0.0005
lr_net: 0.0005
weight_decay: 0.0
disable_cuda: False
log_dir: './runs/12_shapes'
num_features: 16
image_size: 192
state_dict_dir_net: ''
freeze_epochs: 10
dir_for_saving_images: 'visualization_results_shapes'
disable_pretrained: False
weighted_loss: False
seed: 1
gpu_ids: '3'
num_workers: 4
bias: False
extra_test_image_folder: './experiments'
pretrained_checkpoints_dir: './runs/12_shapes'
resume_training: False
model: 'count_pipnet'
use_mid_layers: True
num_stages: 3
max_count: 3
use_ste: True
activation: 'gumbel_softmax'
